# Generated by Django 3.0.4 on 2020-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='d_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('hospital', models.CharField(blank=True, default='', max_length=100)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('fro', models.CharField(blank=True, default='', max_length=100)),
                ('to', models.CharField(blank=True, default='', max_length=100)),
                ('exp_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=13)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('specialization', models.CharField(blank=True, default='', max_length=100)),
                ('highestqualification', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
