# Generated by Django 3.0.4 on 2020-04-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200401_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Role',
            new_name='role',
        ),
    ]
