# Generated by Django 3.0.4 on 2020-04-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
