# Generated by Django 3.0.4 on 2020-04-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200401_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='d_experience',
        ),
    ]
