# Generated by Django 3.0.4 on 2020-04-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
    ]
