# Generated by Django 3.0.4 on 2020-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200415_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment_booking',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='appointment_booking',
            name='appointment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
