# Generated by Django 3.0.4 on 2020-04-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_patient_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
