# Generated by Django 3.0.4 on 2020-04-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='d_name',
        ),
    ]
